spring.application.name=ventas-service
server.port=${PORT:8082}
cliente-service.url=${CLIENTE_SERVICE_URL:http://localhost:8081/api/clientes}
producto-service.url=${PRODUCTO_SERVICE_URL:http://localhost:8180/api/productos}
inventario-service.url=${INVENTARIO_SERVICE_URL:http://localhost:8083/api/inventario}
notificaciones-service.url=${NOTIFICACIONES_SERVICE_URL:http://localhost:8089/api/notificaciones}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/db_minimarket?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Eureka Client
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
management.endpoints.web.exposure.include=health,info


# Railway: permite desactivar Eureka si usas URLs directas
eureka.client.enabled=${EUREKA_CLIENT_ENABLED:true}
