spring.application.name=ventas-service
server.port=8082
cliente-service.url=http://localhost:8090/api/clientes
producto-service.url=http://localhost:8180/api/productos
inventario-service.url=http://localhost:8083/api/inventario
notificaciones-service.url=http://localhost:8089/api/notificaciones

spring.datasource.url=jdbc:mysql://localhost:3306/db_minimarket
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
